# Settings for Rust Workspace 
# [Cargo Manifest Configuration Reference](https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section)

[workspace]
members = ["libraire", "script1", "script2"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
unused = { level = "allow", priority = -1 } # (early) ¡DEVELOPMENT-ONLY!
dead_code = "allow"                         # (early) ¡DEVELOPMENT-ONLY!


[workspace.dependencies]
## --General--
derive_more = "1"
## --Trace-Logging--
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["chrono", "env-filter"] }
## --CLI--
clap = { version = "4.5", features = ["env", "derive", "string", "wrap_help"] }
owo-colors = "4"
indicatif = "0.17"
dialoguer = "0.11"

## --Test Trace-Logging--
test-log = { version = "0.2", features = ["trace"] }
## --Property Sample Testing--
quickcheck = "1"
quickcheck_macros = "1"
