
# Settings for Rust Workspace 
# [Cargo Manifest Configuration Reference](https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section)

[workspace]
members = [
    "lib_blocking",
    "bin_cli",
    "bin_tbd",
    "xp-drop",
    "xp-serde",
    "xp-template",
    "samples_tracing",
    "samples_sync",
    "samples_ptr",
    "samples_mutability",
]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["Ethan Skowronski-Lutz"]
description = "template workspace; explorative"
homepage = "https://github.com/ethanmsl/template-workspace"
documentation = "https://github.com/ethanmsl/template-workspace"
repository = "https://github.com/ethanmsl/template-workspace"
keywords = ["template", "workspace", "explorative"]
# publish = []
# license = ""
# license-file = ""

[workspace.lints.rust]
unsafe_code = "forbid"
unused = { level = "allow", priority = -1 } # (early) ¡DEVELOPMENT-ONLY!
dead_code = "allow"                         # (early) ¡DEVELOPMENT-ONLY!

[workspace.lints.clippy]
allow_attributes = "warn"


[workspace.dependencies]
## --Async--
# futures = "0.3"
tokio = { version = "1", features = ["full", "tracing"] }

## --CLI--
clap = { version = "4", features = [
    "env",
    "derive",
    "string",
    "unicode",
    "wrap_help",
] }
dialoguer = "0.11"
owo-colors = "4"
indicatif = "0.17"

## --Diagnostics--
tracing = "0.1"
# tracing-appender = "0.2"
tracing-error = "0.2"
tracing-timing = "0.6"
tracing-tree = { version = "0.4.0", features = ["time"] }
tracing-subscriber = { version = "0.3", features = ["chrono", "env-filter"] }

## --Env & Files--
csv = "1"
dotenvy = "0.15"
# include_dir = "0.7"
secrecy = "0.8"
walkdir = "2"

## --Explore--
backon = { version = "1", features = ["tokio-sleep"] }
minijinja = { version = "2", default-features = false }

## --General--
bon = "2"
chrono = { version = "0.4", features = ["serde"] }
derive_more = { version = "1", features = [
    "full",
    "constructor",
    "error",
    "deref",
    "from",
] }
itertools = "0.13"
regex = { version = "1", features = ["logging"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

## --Networking--
reqwest = { version = "0.12", features = ["blocking", "json"] }

# Dev-Dependencies
## --Property Sample Testing--
quickcheck = "1"
quickcheck_macros = "1"
## --Test Trace-Logging--
test-log = { version = "0.2", features = ["trace"] }
