[workspace]
members = ["libraire", "script1", "script2"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = { level = "forbid", priority = -1 }
unused = "allow"
dead_code = "allow"                               # (early) ¡DEVELOPMENT-ONLY!
