# Settings for typos-cli tool
# [Typos Configuraiton Reference](https://github.com/crate-ci/typos/blob/master/docs/reference.md)
#
# Syntax: .gitignore glob syntax
#        `*`    : match any file in a single level
#        `**`   : recursively match
#        `**/*` : specifies any _files_ at any level (subtly & potentially different)

[default.extend-words]
libraire = "libraire"

[files]
extend-exclude = ["**/data/**"]
