[package]
name = "xp-drop"
version = "0.1.0"
edition = "2021"
description = "`drop` implementation"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
